### ISSUE TITLE
User HOME is undefined error

### ISSUE THREAD

**Issue by eugfir** [janbar/libobksftp#5]
Hello,

I trying to use the obksftp to backup from RMAN on Windows to an Oracle Linux 7 server over ssh. I have the passwordless ssh login from Windows to the Linux server working for the user obk, but the allocate channel RMAN test command is failing with the following error:

RMAN> allocate channel for maintenance  DEVICE TYPE 'SBT_TAPE' PARMS 'SBT_LIBRARY=D:\obk\obksftp.dll.win64,ENV=(OB_SERVER=ol7s,OB_USER=obk,OB_PATH=/d01/obk/sbt)';

RMAN-00571: ===========================================================
RMAN-00569: =============== ERROR MESSAGE STACK FOLLOWS ===============
RMAN-00571: ===========================================================
RMAN-03009: failure of allocate command on ORA_MAINT_SBT_TAPE_6 channel at 05/15/2025 17:11:44
ORA-19554: error allocating device, device type: SBT_TAPE, device name:
ORA-27023: skgfqsbi: media manager protocol error
ORA-19511: non RMAN, but media manager or vendor specific failure, error text:
   User HOME is undefined

How to set the HOME variable correctly in my case scenario?

Thanks,
-Eugene

**Comment by janbar** [comment]
On Windows the HOME variable is estimated from HOMEDRIVE and HOMEPATH. It is used to find the default store of the SSH keys, i.e `%HOMEDRIVE%%HOMEPATH%\.ssh`.

It seems in your case those variables are not defined. The workaround is to specify the location of the SSH key files, by setting OB_PUBLIC_KEY and OB_SECRET_KEY, as follows:

PARMS 'SBT_LIBRARY=D:\obk\obksftp.dll.win64,ENV=(**OB_PUBLIC_KEY=C:\publickeyfilepath**,**OB_SECRET_KEY=C:\privatekeyfilepath**,OB_SERVER=ol7s,OB_USER=obk,OB_PATH=/d01/obk/sbt)'

If you want use the default path for the key store (HOME/.ssh), the variable HOMEDRIVE and HOMEPATH must be set. The source code is:
```
#ifdef __WINDOWS__
  if (strlen(name) == 4 && strncmp(name, "HOME", 4) == 0)
  {
    if ((env = getenv("HOMEDRIVE")) == NULL)
      return 0;
    strncpy(buf, env, maxlen - 1);
    if ((env = getenv("HOMEPATH")) == NULL)
      return 0;
    strncat(buf, env, maxlen - strlen(buf) - 1);
    return strlen(buf);
  }
#endif
```
So if your SSH keys are stored in `%HOMEDRIVE%%HOMEPATH%\.ssh`, then an other way is to set the variables HOMEDRIVE and HOMEPATH in params like the following:

PARMS 'SBT_LIBRARY=D:\obk\obksftp.dll.win64,ENV=(**HOMEDRIVE=C:**,**HOMEPATH=\Users\MyUserName**,OB_SERVER=ol7s,OB_USER=obk,OB_PATH=/d01/obk/sbt)'

**Comment by eugfir** [comment]
Hi Jean,

I tried both ways you suggested but unfortunately neither of them worked spitting out 'SSH error -19: Authentication by public key failed':

RMAN> allocate channel for maintenance  DEVICE TYPE 'SBT_TAPE' PARMS 'SBT_LIBRARY=D:\obk\obksftp.dll.win64,ENV=(HOMEDRIVE=C:,HOMEPATH=\Users\eugfir,OB_SERVER=ol7s,OB_USER=obk,OB_PATH=/d01/obk/sbt)';

RMAN-00571: ===========================================================
RMAN-00569: =============== ERROR MESSAGE STACK FOLLOWS ===============
RMAN-00571: ===========================================================
RMAN-03009: failure of allocate command on ORA_MAINT_SBT_TAPE_11 channel at 05/16/2025 09:09:22
ORA-19554: error allocating device, device type: SBT_TAPE, device name:
ORA-27023: skgfqsbi: media manager protocol error
ORA-19511: non RMAN, but media manager or vendor specific failure, error text:
   SSH error -19: Authentication by public key failed

RMAN> allocate channel for maintenance  DEVICE TYPE 'SBT_TAPE' PARMS 'SBT_LIBRARY=D:\obk\obksftp.dll.win64,ENV=(OB_PUBLIC_KEY=C:\Users\eugfir\.ssh\id_rsa.pub,OB_SECRET_KEY=C:\Users\eugfir\.ssh\id_rsa,OB_SERVER=ol7s,OB_USER=obk,OB_PATH=/d01/obk/sbt)';

RMAN-00571: ===========================================================
RMAN-00569: =============== ERROR MESSAGE STACK FOLLOWS ===============
RMAN-00571: ===========================================================
RMAN-03009: failure of allocate command on ORA_MAINT_SBT_TAPE_12 channel at 05/16/2025 09:14:45
ORA-19554: error allocating device, device type: SBT_TAPE, device name:
ORA-27023: skgfqsbi: media manager protocol error
ORA-19511: non RMAN, but media manager or vendor specific failure, error text:
   SSH error -19: Authentication by public key failed

Setting the HOMEDRIVE and HOMEPATH env vars for the RMAN's CMD session and in the Windows Registry for the user also did not work:

C:\Windows\system32>set HOMEDRIVE=C:

C:\Windows\system32>set HOMEPATH=\Users\eugfir

C:\Windows\system32>echo %HOMEDRIVE%
C:

C:\Windows\system32>echo %HOMEPATH%
\Users\eugfir

C:\Windows\system32>rman target /

Recovery Manager: Release 19.0.0.0.0 - Production on Fri May 16 09:26:16 2025
Version 19.23.0.0.0

Copyright (c) 1982, 2024, Oracle and/or its affiliates.  All rights reserved.

connected to target database: CCTL (DBID=3546030209)

RMAN> allocate channel for maintenance  DEVICE TYPE 'SBT_TAPE' PARMS 'SBT_LIBRARY=D:\obk\obksftp.dll.win64,ENV=(OB_SERVER=ol7s,OB_USER=obk,OB_PATH=/d01/obk/sbt)';

using target database control file instead of recovery catalog
RMAN-00571: ===========================================================
RMAN-00569: =============== ERROR MESSAGE STACK FOLLOWS ===============
RMAN-00571: ===========================================================
RMAN-03009: failure of allocate command on ORA_MAINT_SBT_TAPE_1 channel at 05/16/2025 09:26:32
ORA-19554: error allocating device, device type: SBT_TAPE, device name:
ORA-27023: skgfqsbi: media manager protocol error
ORA-19511: non RMAN, but media manager or vendor specific failure, error text:
   User HOME is undefined

I still can connect passwordless to the remote Linux host from the Windows account (eugfir) running RMAN interface:

C:\Windows\system32>ssh obk@ol7s
Last login: Thu May 15 16:54:03 2025 from w10a.mshome.net
[obk@ol7s ~]$

Any other idea?

Thank you,
-Eugene

**Comment by janbar** [comment]
Checking, there is an issue with the lib 1.0.11.0 bold for Windows. It seems the crypto backend provided by the OS no longer works from sometime.
So I pushed a new tag 1.0.11.2 with the fixed lib for Windows. It is statically linked with OpenSSL, and so it is bigger. But it works as expected and no longer depend of the Windows crypto backend (WinCNG).

https://github.com/janbar/libobksftp/releases/tag/1.0.11.2

Please let me know if that fixes the issue for you.

**Comment by eugfir** [comment]
Hi Jean,

Unfortunately the new lib 1.0.11.2 you provided is still failing with "SSH error -16: Authentication by public key failed". In contrast, it's
working fine on RMAN/Linux (OL7) as I tested earlier. Looks like something is still missing in my configuration if you say you made it work on your test Windows environment.

Thanks,
-Eugene

**Comment by eugfir** [comment]
Hi Jean,

The log file is attached.

[objectanalysisro.xlsx](https://github.com/user-attachments/files/20276874/objectanalysisro.xlsx)

Thanks,
-Eugene

**Comment by eugfir** [comment]
[obksftp_test.log.7308.txt](https://github.com/user-attachments/files/20276881/obksftp_test.log.7308.txt)

**Comment by janbar** [comment]
Your log file seems to be OK. I guess the SBT TEST succeeded.

**Comment by eugfir** [comment]
Hi Jean,

Even though the sbttest succeeds as per your observation of the sbttest log, the RMAN command to SBT is still failing on me with the "SSH error -16: Authentication by public key failed" using the latest obksftp build. S

[obksftp_test.log.6236.txt](https://github.com/user-attachments/files/20300802/obksftp_test.log.6236.txt)

Besides sbttest, can you please try to run some command from RMAN like "allocate channel to SBT/obksftp", i.e. similar to what I am trying, to see if it works in your Windows/RMAN environment?

Thanks,
-Eugene

**Comment by janbar** [comment]
The first possible cause of your issue is the RSA key is not readable by the oracle process. May be the instance is started with an account that is not allowed to read your key files.

Therefore, you have to check the key files are readable by the account used to start the oracle database instance.

**Comment by eugfir** [comment]
Hi Jean,

The RMAN backup to obksftp is working now after making the SSH key files readable to the local Oracle instance service DBA group.
There is one issue thought with backup set files: the backup file names don't seem to follow the OB_PATH=/d01/obk/sbt backup file directory destination prefixing the "sbt\..." to the backup piece file names like this and ignoring the sbt subdirectory: 

[obk@ol7s obk]$ ll -R
.:
total 22528
drwxrwxr-x 2 obk obk        6 May 15 15:19 sbt
-rw-r----- 1 obk obk   262144 May 19 09:55 sbt\5v3pr9l5_1_1
-rw-r----- 1 obk obk   262144 May 19 10:22 sbt\643prb6d_1_1
-rw-r----- 1 obk obk 11272192 May 19 09:55 sbt\c-3546030209-20250519-00
-rw-r----- 1 obk obk 11272192 May 19 10:22 sbt\c-3546030209-20250519-01

./sbt:
total 0

As the result, RMAN cannot find the backup pieces, for example:

RMAN> delete backup of spfile;

allocated channel: ORA_DISK_1
channel ORA_DISK_1: SID=381 device type=DISK
allocated channel: ORA_SBT_TAPE_1
channel ORA_SBT_TAPE_1: SID=626 device type=SBT_TAPE
channel ORA_SBT_TAPE_1: WARNING: Oracle Test Disk API

List of Backup Pieces
BP Key  BS Key  Pc# Cp# Status      Device Type Piece Name
------- ------- --- --- ----------- ----------- ----------
107     89      1   1   AVAILABLE   SBT_TAPE    5v3pr9l5_1_1
108     90      1   1   AVAILABLE   SBT_TAPE    c-3546030209-20250519-00
109     91      1   1   AVAILABLE   SBT_TAPE    643prb6d_1_1
110     92      1   1   AVAILABLE   SBT_TAPE    c-3546030209-20250519-01

Do you really want to delete the above objects (enter YES or NO)? y

RMAN-06207: warning: 4 objects could not be deleted for SBT_TAPE channel(s) due
RMAN-06208:          to mismatched status.  Use CROSSCHECK command to fix status
RMAN-06210: List of Mismatched objects
RMAN-06211: ==========================
RMAN-06212:   Object Type   Filename/Handle
RMAN-06213: --------------- ---------------------------------------------------
RMAN-06214: Backup Piece    5v3pr9l5_1_1
RMAN-06214: Backup Piece    c-3546030209-20250519-00
RMAN-06214: Backup Piece    643prb6d_1_1
RMAN-06214: Backup Piece    c-3546030209-20250519-01

because it's expecting the backup pieces just without the "sbt\" substring:

List of Backup Sets
===================


BS Key  Type LV Size       Device Type Elapsed Time Completion Time
------- ---- -- ---------- ----------- ------------ -------------------
89      Full    256.00K    SBT_TAPE    00:00:00     2025-05-19 09:55:49
        BP Key: 107   Status: AVAILABLE  Compressed: NO  Tag: TAG20250519T095549
        Handle: 5v3pr9l5_1_1   Media: 06E33362
  SPFILE Included: Modification time: 2025-05-19 09:22:21
  SPFILE db_unique_name: CCTL

BS Key  Type LV Size       Device Type Elapsed Time Completion Time
------- ---- -- ---------- ----------- ------------ -------------------
90      Full    10.75M     SBT_TAPE    00:00:00     2025-05-19 09:55:51
        BP Key: 108   Status: AVAILABLE  Compressed: NO  Tag: TAG20250519T095551
        Handle: c-3546030209-20250519-00   Media: 06E33362
  SPFILE Included: Modification time: 2025-05-19 09:22:21
  SPFILE db_unique_name: CCTL

BS Key  Type LV Size       Device Type Elapsed Time Completion Time
------- ---- -- ---------- ----------- ------------ -------------------
91      Full    256.00K    SBT_TAPE    00:00:00     2025-05-19 10:22:05
        BP Key: 109   Status: AVAILABLE  Compressed: NO  Tag: TAG20250519T102205
        Handle: 643prb6d_1_1   Media: 06E33362
  SPFILE Included: Modification time: 2025-05-19 10:01:21
  SPFILE db_unique_name: CCTL

BS Key  Type LV Size       Device Type Elapsed Time Completion Time
------- ---- -- ---------- ----------- ------------ -------------------
92      Full    10.75M     SBT_TAPE    00:00:00     2025-05-19 10:22:06
        BP Key: 110   Status: AVAILABLE  Compressed: NO  Tag: TAG20250519T102206
        Handle: c-3546030209-20250519-01   Media: 06E33362
  SPFILE Included: Modification time: 2025-05-19 10:01:21
  SPFILE db_unique_name: CCTL

RMAN>

Looks like being a bug to me.

Thanks,
-Eugene

**Comment by janbar** [comment]
There is a BUG with Win64. It is my fault: The SFTP specifications said:
> This protocol represents file names as strings. File names are assumed to use the slash ('/') character as a directory separator.

So the backup piece name must be prefixed by "/" and not the platform separator (on Windows it is "\\"). I will fix it soon.

**Comment by eugfir** [comment]
That's great but make sure the fix works for both Windows and Linux remote "storage" hosts where RMAN sends the backup files to :-)

**Comment by janbar** [comment]
I fixed the issue relative to Win64 with the release 1.0.11.4 of the build.
It doesn't impact the others platforms as they are compliant with the SFTP standard ;-). So only Windows had this BUG, and I had a reminder for that (from 2 years!). As nobody use it on Windows, until now! , I remained lazy.

I will push a TAG later, when you will have time to test it.

Note: In all case the SFTP server uses the slash (/) as path separator, even on Windows. In example to specify the path "C:\Temp\dummy", you have to use the string "/C/Temp/dummy" as it is specified by the protocol.
Therefore the variable OB_PATH must be compliant with SFTP (only slash), and the RMAN format string must too.

**Comment by eugfir** [comment]
Hi Jean,

It's working as expected now creating the backup file names correctly on my Linux remote host over SSH in the OB_PATH location.

With Best Regards!
-Eugene
